Comp imu [draft 5]
swift-nav/libsbp pull request #1446
Opened 2024-10-01 23:35 UTC by ismolyakov

# Description

@swift-nav/algint-team

# API compatibility

Does this change introduce a API compatibility risk?

## API compatibility plan

If the above is "Yes", please detail the compatibility (or migration) plan:

# JIRA Reference

https://swift-nav.atlassian.net/browse/BOARD-XXXX

2024-10-02 01:50 UTC, junc52 approved these changes
Thanks for resolving challenging work!
Question : so updating imu.yaml will produce all these changes automatically?

2024-10-02 15:12 UTC, ismolyakov commented
> Thanks for resolving challenging work! Question : so updating imu.yaml will produce all these changes automatically?

Yes! the intended process is:
- define the message specs
- run `make all` and all code _should_ be generated (this is not what I encountered: while the scripts of a given Docker image on a given machine may succeed, the pipeline items may fail - I am still in progress to identify the best recipe that leads to passing pipeline)

2024-10-03 00:11 UTC, pcrumley requested changes
Can you remove the link to the internal confluence documentation from you PR description?

I'm also curious about this statement: "This PR doesn't include a corresponding unit test due to test generation problems. It is proposed to merge as is to unblock development and address test generation as the next step."  Do you need help/advice on how to do the unit test or are you struggling to generate the input data for the messages?

Finally, can you close all the draft PRs? 
#1441
#1442 
#1443 
#1444
#1445

2024-10-03 02:42 UTC, pcrumley approved these changes

2024-10-03 13:03 UTC, merged