python: use extras feature for jit/aot
swift-nav/libsbp pull request #894
Opened 2020-12-15 08:43 UTC by silverjam

2021-01-18 18:15 UTC, john-michaelburke requested changes

2021-01-19 19:01 UTC, silverjam commented on python/deploy.py
> +        raise RuntimeError("Unsupported Python version")
🛠️

2021-01-19 19:24 UTC, john-michaelburke approved these changes

2021-01-28 04:21 UTC, merged

2021-01-28 04:23 UTC, silverjam commented
Should also fix https://swift-nav.atlassian.net/browse/INFRA-308