Turn on auto formatting
swift-nav/libsbp pull request #954
Opened 2021-04-21 04:55 UTC by woodfell

Enable the clang-format cmake module and run during generation of C source/headers. `.clang-format` imported from Starling.

Adjust the C header template slightly to achieve the following:
- documentation comments are attached to the struct for a message rather than the #define for the message ID
- documentation comments for struct members are placed preceding the member rather than trailing to prevent excessive line breaks and poor formatting

There are no functional changes in this PR. The only places which were edited by hand are:
- Makefile
- c/CMakeLists.txt
- generator/sbpg/targets/resources/sbp_messages_template.h
- c/include/cpp/state.h (shuffling some // NOLINTs)

2021-04-21 14:23 UTC, reimerix requested changes
I think the current build image might not include `clang-format`, here is a snippet from running `make -j8 c` using the `swiftnav/libsbp-build:2021.04.02` image on my machine:

```
CMake Warning at cmake/common/ClangFormat.cmake:122 (message):
  Could not find appropriate clang-format, targets disabled
Call Stack (most recent call first):
  cmake/common/ClangFormat.cmake:218 (early_exit)
  CMakeLists.txt:13 (swift_setup_clang_format)
```

2021-04-22 23:54 UTC, silverjam commented
@woodfell please update the README.md/HOWTO.md to point to the new docker image tag

2021-04-23 07:46 UTC, reimerix approved these changes
LGTM

2021-04-23 22:42 UTC, silverjam approved these changes

2021-04-24 00:11 UTC, jbangelo commented
What's the motivation to remove the empty structs? I can't think of a reason to have included them in the first place, but removing them is a breaking change.

2021-04-25 11:16 UTC, woodfell commented
> What's the motivation to remove the empty structs? I can't think of a reason to have included them in the first place, but removing them is a breaking change.

Oops, getting ahead of myself here. Empty structs are one of the problems in libsbp but I'll put them back in for the moment

2021-04-26 01:36 UTC, merged

2021-04-26 17:20 UTC, denniszollo commented on c/include/libsbp/acquisition.h
> +   */
this is objectively more pretty before than it is after.  It used to be visible in 5 lines, now it takes 25,.